# playbook.yml

- hosts: web
  become: true
  vars:
    nginx_package: nginx
    nginx_service: nginx
  tasks:
    - name: Atualizar lista de pacotes apt
      apt:
        update_cache: yes

    - name: Atualizar todos os pacotes
      apt:
        upgrade: dist

    - name: Install nginx
      apt:
        name: "{{ nginx_package }}"
        state: present
      notify:
        - Restart nginx

    - name: Enable and start nginx
      service:
        name: "{{ nginx_service }}"
        enabled: yes
        state: started
        
  handlers:
    - name: Restart nginx
      service:
        name: "{{ nginx_service }}"
        state: restarted