name: 'Terraform'

on:
  push:
    branches: 
      - main
#    paths:
#      - terraform/**
#      - ansible/**

permissions:
  contents: read


env:
 # verbosity setting for Terraform logs
 TF_LOG: INFO

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./terraform
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.6.5
        
    - name: Terraform Init
      id: init
      run: terraform init -upgrade

    - name: Terraform Format
      id: fmt
      run: terraform fmt -check

    - name: Terraform Validate
      id: validate
      run: terraform validade
    
    - name: Terraform Plan
      id: plan
      run: terraform plan -out apply.tfplan -var-file=student.tfvars
  
    - name: Terraform Apply      
      id: apply
      run: terraform apply apply.tfplan